# Generated by Django 3.2.4 on 2021-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0003_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='total_marks',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
